name: badminton_management_1
description: "A new Flutter project."
# publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.0
  crypto: ^3.0.6
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localization: ^0.2.2
  geolocator: ^13.0.1
  google_fonts: ^6.2.1
  html: ^0.15.4
  http: ^1.2.2
  intl: ^0.19.0
  loading_animation_widget: ^1.3.0
  mailer: ^6.2.0
  month_picker_dialog: ^5.1.3
  path: ^1.9.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  quickalert: ^1.1.0
  sqflite: ^2.4.0
  table_calendar: ^3.1.2
  timezone: ^0.9.4
  url_launcher: ^6.3.1
  weather_animation: ^1.1.0
  webview_flutter: ^4.10.0
  youtube_explode_dart: ^2.3.5
  youtube_player_flutter: ^9.1.1
  firebase_cloud_messaging_flutter: ^1.0.3
  get: ^4.7.2
  flutter_local_notifications: ^18.0.1
  get_controller_plus: ^0.2.1
  device_info_plus: ^9.1.2
  firebase_messaging: ^15.2.3
  firebase_core: ^3.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/logo_icon/
    - assets/lang/
    - assets/slide_img/
    - google_fonts/Roboto/
